id: TIM - Process Domain Registrar With WHOIS
version: -1
fromversion: 5.5.0
name: TIM - Process Domain Registrar With WHOIS
description: This playbook runs the whois enrichment on domain indicators provided
  by an indicator query such as "type:Domain". The playbook then compares the domain
  registrars against the Cortex XSOAR list provided in the inputs.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 22c564e6-c75c-4709-8fb4-473d3d61807e
    type: start
    task:
      id: 22c564e6-c75c-4709-8fb4-473d3d61807e
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: e8b6a799-2a22-4d66-84fa-66696bc91f35
    type: condition
    task:
      id: e8b6a799-2a22-4d66-84fa-66696bc91f35
      version: -1
      name: Are there query results?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: playbookQuery.value
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: a01e20f3-29f5-4ab4-83ad-454ab189ba87
    type: title
    task:
      id: a01e20f3-29f5-4ab4-83ad-454ab189ba87
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: f90a2267-1595-40d6-87a6-8e25335c3ea2
    type: regular
    task:
      id: f90a2267-1595-40d6-87a6-8e25335c3ea2
      version: -1
      name: Run whois on indicators
      description: Provides data enrichment for domains.
      script: Whois1|||whois
      type: regular
      iscommand: true
      brand: Whois1
    nexttasks:
      '#none#':
      - "4"
      - "13"
    scriptarguments:
      query:
        simple: ${playbookQuery.value}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -860,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: b40a8c3f-0302-4ae7-8874-b1580268f1df
    type: regular
    task:
      id: b40a8c3f-0302-4ae7-8874-b1580268f1df
      version: -1
      name: FilterByList
      description: Checks whether the specified item is in a list. The default list
        is the Cortex XSOAR Indicators Whitelist.
      scriptName: FilterByList
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
      - "24"
    scriptarguments:
      delimiter:
        simple: ${inputs.RegistrarListDelimiter}
      ignorecase:
        simple: "yes"
      listname:
        simple: ${inputs.ApprovedRegistrarsListName}
      matchexact:
        simple: "yes"
      values:
        simple: ${Domain.Whois.Registrar.Name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -70,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 3b71315c-73ff-4b78-887a-eb33d3d55e27
    type: condition
    task:
      id: 3b71315c-73ff-4b78-887a-eb33d3d55e27
      version: -1
      name: Is there an approved registrars list?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.ApprovedRegistrarsListName
            iscontext: true
    view: |-
      {
        "position": {
          "x": 130,
          "y": 240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 061481f3-9fc5-4689-8288-1c00aec0c05d
    type: regular
    task:
      id: 061481f3-9fc5-4689-8288-1c00aec0c05d
      version: -1
      name: Set not-approved domains
      description: Domains whose registrar does not appear in the list defined in inputs.
        ApprovedRegistrarsListName context key are added to NonApprovedDomains in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonApprovedDomains
      stringify: {}
      value:
        complex:
          root: playbookQuery
          filters:
          - - operator: isEqualString
              left:
                value:
                  simple: playbookQuery.indicator_type
                iscontext: true
              right:
                value:
                  simple: Domain
          accessor: value
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 730,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 91c48fed-e49e-4486-85b5-ca787571d27b
    type: condition
    task:
      id: 91c48fed-e49e-4486-85b5-ca787571d27b
      version: -1
      name: Are there domains without Whois query results?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "22"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEqualString
          left:
            value:
              simple: Domain.Whois.QueryResult
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": -860,
          "y": 630
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 08277e99-e1e6-49c1-8ddb-bdc9ce072a2d
    type: regular
    task:
      id: 08277e99-e1e6-49c1-8ddb-bdc9ce072a2d
      version: -1
      name: Set domains without Whois results
      description: Domains with no registrar information are added to NonApprovedDomains in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonApprovedDomains
      stringify: {}
      value:
        complex:
          root: Domain
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: Domain.Whois.QueryResult
                iscontext: true
              right:
                value:
                  simple: "true"
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -990,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: c7a3c947-cfdf-4656-8245-cfbff77ca48e
    type: regular
    task:
      id: c7a3c947-cfdf-4656-8245-cfbff77ca48e
      version: -1
      name: Set domains by approved registrars
      description: Domains whose registrar appears in the list defined in inputs.ApprovedRegistrarsListName context
        key are added to ApprovedDomains in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ApprovedDomains
      stringify: {}
      value:
        complex:
          root: Domain
          filters:
          - - operator: inList
              left:
                value:
                  simple: Domain.Whois.Registrar.Name
                iscontext: true
              right:
                value:
                  simple: List.In
                iscontext: true
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -290,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 371bb257-dce3-46c7-8bf0-c0273a94472c
    type: regular
    task:
      id: 371bb257-dce3-46c7-8bf0-c0273a94472c
      version: -1
      name: Set domains by non approved registrars
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonApprovedDomains
      stringify: {}
      value:
        complex:
          root: Domain
          filters:
          - - operator: inList
              left:
                value:
                  simple: Domain.Whois.Registrar.Name
                iscontext: true
              right:
                value:
                  simple: List.NotIn
                iscontext: true
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: beeb8248-9272-45fb-8874-30d2e06bf64a
    type: title
    task:
      id: beeb8248-9272-45fb-8874-30d2e06bf64a
      version: -1
      name: No registrar list provided
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 730,
          "y": 420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: e3ac3676-405c-4fad-8bfd-8374fa33356b
    type: title
    task:
      id: e3ac3676-405c-4fad-8bfd-8374fa33356b
      version: -1
      name: Domain not found by Whois
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -990,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: 31c23415-0ec9-4f59-81fa-b221094cb371
    type: title
    task:
      id: 31c23415-0ec9-4f59-81fa-b221094cb371
      version: -1
      name: Domain registrar in approved list
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -290,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: a2907802-7f62-49de-886a-f23ee2148b5a
    type: title
    task:
      id: a2907802-7f62-49de-886a-f23ee2148b5a
      version: -1
      name: Domain registrar not in approved list
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 180,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1345,
        "width": 2100,
        "x": -990,
        "y": -80
      }
    }
  }
inputs:
- key: ""
  value: {}
  required: false
  description: ""
  playbookInputQuery:
    query: ""
    queryEntity: indicators
    results: null
    daterange:
      fromdate: 0001-01-01T00:00:00Z
      todate: 0001-01-01T00:00:00Z
      period:
        by: ""
        byto: ""
        byfrom: ""
        tovalue: null
        fromvalue: null
        field: ""
      fromdatelicenseval: 0001-01-01T00:00:00Z
    runFromLastJobTime: false
- key: ApprovedRegistrarsListName
  value: {}
  required: false
  description: The Cortex XSOAR list name that contains the approved registrars.
- key: RegistrarListDelimiter
  value: {}
  required: false
  description: |-
    A one-character string used to delimit fields. This must match the value that you defined in the list separator server configuration.  
    The default value is a comma, however, as registrars might contain the "," character in their name, 
    Cortex XSOAR recommends that you select a different delimiter.
  playbookInputQuery: null
outputs:
- contextPath: NonApprovedDomains
  description: Domains for which the registrar isn't approved.
  type: string
- contextPath: ApprovedDomains
  description: Domains for which the registrar is approved.
  type: string
quiet: true
tests:
- No test
