id: TIM - Process Domain Registrant With Whois
version: -1
fromversion: 5.5.0
name: TIM - Process Domain Registrant With Whois
description: This playbook compares the domain registrant against the Cortex XSOAR
  list provided in the inputs. A registrant is the company or entity that owns the
  domain.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 416a64c6-a933-4459-8880-67c8237586dd
    type: start
    task:
      id: 416a64c6-a933-4459-8880-67c8237586dd
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 3fa9b3ef-4fa9-439d-8f50-409a63bd3abc
    type: condition
    task:
      id: 3fa9b3ef-4fa9-439d-8f50-409a63bd3abc
      version: -1
      name: Are there query results?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: Results
            iscontext: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 70
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: ca3a145e-45a6-46a8-851a-425fe0ae1104
    type: title
    task:
      id: ca3a145e-45a6-46a8-851a-425fe0ae1104
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1200
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 409e4d28-2e62-4095-8687-29e3c1cc5d24
    type: regular
    task:
      id: 409e4d28-2e62-4095-8687-29e3c1cc5d24
      version: -1
      name: FilterByList
      description: Checks whether the specified item is in a list. The default list
        is the Cortex XSOAR Indicators Whitelist.
      scriptName: FilterByList
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
      - "24"
    scriptarguments:
      delimiter:
        simple: ${inputs.registrantListDelimiter}
      ignorecase:
        simple: "yes"
      listname:
        simple: ${inputs.ApprovedregistrantsListName}
      matchexact:
        simple: "yes"
      values:
        simple: ${Results.Whois.Registrant.organization}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -70,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: ea9db6a0-cbe0-432b-86c0-2189f44e9dfb
    type: condition
    task:
      id: ea9db6a0-cbe0-432b-86c0-2189f44e9dfb
      version: -1
      name: Is there an approved registrants list?
      type: condition
      iscommand: false
      brand: ""

    nexttasks:
      '#default#':
      - "21"
      "yes":
      - "13"
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              simple: inputs.ApprovedregistrantsListName
            iscontext: true
    view: |-
      {
        "position": {
          "x": -60,
          "y": 270
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: e547deec-31ab-4aac-866a-3b6ffe9e3906
    type: regular
    task:
      id: e547deec-31ab-4aac-866a-3b6ffe9e3906
      version: -1
      name: Set non tested domains
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NotTestedDomains
      stringify: {}
      value:
        complex:
          root: Results
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 730,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 5e36ad8a-1271-4fbf-8124-0663b0cd4660
    type: condition
    task:
      id: 5e36ad8a-1271-4fbf-8124-0663b0cd4660
      version: -1
      name: Are there domains without Whois query results?
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "22"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEqualString
          left:
            value:
              simple: Results.Whois.QueryResult
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": -950,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: f5ecad72-7e2a-4619-882b-efe72d7f2f22
    type: regular
    task:
      id: f5ecad72-7e2a-4619-882b-efe72d7f2f22
      version: -1
      name: Tag domain with no Whois result
      description: Tag indicator with the no_whois_result tag.
      script: Builtin|||appendIndicatorField
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: no_whois_value
      indicatorsValues:
        simple: ${DomainsNotResolvedByWhois}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -1050,
          "y": 1010
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "19":
    id: "19"
    taskid: 39fe185c-642b-4444-88de-3ed07a4806e5
    type: regular
    task:
      id: 39fe185c-642b-4444-88de-3ed07a4806e5
      version: -1
      name: Set domains by approved registrants
      description: Domains whose registrant appears in the list defined in inputs.ApprovedregistrantsListName
        context key are added to ApprovedDomains in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "26"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: ApprovedRegistrantDomains
      stringify: {}
      value:
        complex:
          root: Results
          filters:
          - - operator: inList
              left:
                value:
                  simple: Results.Whois.Registrant.organization
                iscontext: true
              right:
                value:
                  simple: List.In
                iscontext: true
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -240,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: ac8f990e-836a-4215-85a0-0e721776151b
    type: regular
    task:
      id: ac8f990e-836a-4215-85a0-0e721776151b
      version: -1
      name: Set domains by non approved registrants
      description: Checks if the specified value exists in context. If the value exists,
        it will be set in context, otherwise no value will be set in context.
      scriptName: SetAndHandleEmpty
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: NonApprovedRegistrantDomains
      stringify: {}
      value:
        complex:
          root: Results
          filters:
          - - operator: inList
              left:
                value:
                  simple: Results.Whois.Registrant.organization
                iscontext: true
              right:
                value:
                  simple: List.NotIn
                iscontext: true
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: cb1a7ce3-0c22-4b75-8529-453ed37b85a6
    type: title
    task:
      id: cb1a7ce3-0c22-4b75-8529-453ed37b85a6
      version: -1
      name: No registrant list provided
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "8"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 730,
          "y": 480
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: 8287a40c-3f55-4706-8e92-007fae6f7d80
    type: title
    task:
      id: 8287a40c-3f55-4706-8e92-007fae6f7d80
      version: -1
      name: Domain not found by Whois
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "27"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -1050,
          "y": 730
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: c4b4d2db-75c1-4f03-8906-95733f76919b
    type: title
    task:
      id: c4b4d2db-75c1-4f03-8906-95733f76919b
      version: -1
      name: Domain registrant in approved list
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "19"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -240,
          "y": 655
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "24":
    id: "24"
    taskid: 6e9eac1d-9674-4cf0-8bfd-b5ecc13d79b3
    type: title
    task:
      id: 6e9eac1d-9674-4cf0-8bfd-b5ecc13d79b3
      version: -1
      name: Domain registrant not in approved list
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "20"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 210,
          "y": 655
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "25":
    id: "25"
    taskid: ced367cb-b7ab-4018-86fb-16c5c73c0136
    type: regular
    task:
      id: ced367cb-b7ab-4018-86fb-16c5c73c0136
      version: -1
      name: Set Results
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Results
      stringify: {}
      value:
        simple: ${inputs.WhoisResults}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": -90
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "26":
    id: "26"
    taskid: 2388288d-3f2a-46e6-8f26-189e66ac3fe8
    type: regular
    task:
      id: 2388288d-3f2a-46e6-8f26-189e66ac3fe8
      version: -1
      name: Tag as approved registrant
      description: tags the indicatorwith the approved_registrant tag.
      script: Builtin|||appendIndicatorField
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      field:
        simple: tags
      fieldValue:
        simple: approved_registrant
      indicatorsValues:
        simple: ${ApprovedRegistrantDomains}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -240,
          "y": 1000
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "27":
    id: "27"
    taskid: 1b1f490a-f599-448b-82d2-aec2b435d99f
    type: regular
    task:
      id: 1b1f490a-f599-448b-82d2-aec2b435d99f
      version: -1
      name: Set domains without Whois results
      description: Sets a value into the context with the given context key
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: DomainsNotResolvedByWhois
      stringify: {}
      value:
        complex:
          root: Results
          filters:
          - - operator: isNotEqualString
              left:
                value:
                  simple: Results.Whois.QueryResult
                iscontext: true
              right:
                value:
                  simple: "true"
          accessor: Whois.QueryValue
          transformers:
          - operator: uniq
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -1050,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1505,
        "width": 2160,
        "x": -1050,
        "y": -240
      }
    }
  }
inputs:
- key: ""
  value: {}
  required: false
  description: ""
  playbookInputQuery:
    query: ""
    queryEntity: indicators
    results: null
    daterange:
      fromdate: 0001-01-01T00:00:00Z
      todate: 0001-01-01T00:00:00Z
      period:
        by: ""
        byto: ""
        byfrom: ""
        tovalue: null
        fromvalue: null
        field: ""
      fromdatelicenseval: 0001-01-01T00:00:00Z
    runFromLastJobTime: false
- key: ApprovedregistrantsListName
  value: {}
  required: false
  description: The Cortex XSOAR list name that contains the approved registrars.  A
    registrant is the company or entity  that owns the domain.
  playbookInputQuery: null
- key: registrantListDelimiter
  value: {}
  required: false
  description: |-
    A one-character string used to delimit fields. This must match the value that you defined in the list separator server configuration.
    The default value is a comma, however, as registrants might contain the "," character in their name,
    Cortex XSOAR recommends that you select a different delimiter.
  playbookInputQuery: null
- key: WhoisResults
  value: {}
  required: false
  description: This input receives the Whois results from the parent playbook.
  playbookInputQuery: null
outputs:
- contextPath: NonApprovedDomains
  description: Domains for which the registrant isn't approved.
  type: string
- contextPath: ApprovedRegistrantDomains
  description: Domains for which the registrant is approved.
  type: string
- contextPath: DomainsNotResolvedByWhois
  description: Domains which Whois wasn't able to resolve.
  type: string
- contextPath: NotTestedDomains
  description: In case no registrant list was provided all domains will be outputted
    here.
  type: string
quiet: true
tests:
- No test