id: Test-debug-mode
version: -1
name: Test-debug-mode
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 43629c57-4889-406f-8dac-8b9b3cc08a59
    type: start
    task:
      id: 43629c57-4889-406f-8dac-8b9b3cc08a59
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 660,
          "y": 30
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 6acecbab-410f-45f0-8236-d164d58d11a4
    type: regular
    task:
      id: 6acecbab-410f-45f0-8236-d164d58d11a4
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 660,
          "y": 250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: c234f4fd-56b9-497f-8403-2fd98440b4b7
    type: regular
    task:
      id: c234f4fd-56b9-497f-8403-2fd98440b4b7
      version: -1
      name: Py logging first time
      scriptName: TestPyLogging
      type: regular
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 660,
          "y": 430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 41806431-8fb8-412b-8628-5bff8a296717
    type: regular
    task:
      id: 41806431-8fb8-412b-8628-5bff8a296717
      version: -1
      name: PyLogging in debug-mode
      description: Run executeCommand in a generic manner. Can be used to dynamically
        execute a command and also for cases when there is need to pass arguments
        not defined in the command's configuration.
      scriptName: ExecuteCommandGeneric
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      argName1:
        simple: debug-mode
      argName2: {}
      argName3: {}
      argName4: {}
      argName5: {}
      argVal1:
        simple: "true"
      argVal2: {}
      argVal3: {}
      argVal4: {}
      argVal5: {}
      commandName:
        simple: TestPyLogging
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 660,
          "y": 620
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 2cb30111-4450-43a5-8f5a-218ea59a9d16
    type: regular
    task:
      id: 2cb30111-4450-43a5-8f5a-218ea59a9d16
      version: -1
      name: Load Debug File
      description: Load the contents of a file into context.
      scriptName: ReadFile
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      encoding: {}
      entryID:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "1"
      maxFileSize:
        simple: "20000"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 660,
          "y": 820
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: b497f62b-ed13-4948-865f-e9833451c113
    type: condition
    task:
      id: b497f62b-ed13-4948-865f-e9833451c113
      version: -1
      name: Verify Debug Data
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "7"
      "yes":
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsString
          left:
            value:
              simple: FileData
            iscontext: true
          right:
            value:
              simple: logging
    view: |-
      {
        "position": {
          "x": 660,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 96d5c029-f41c-45a2-84ed-1224e24fe6c3
    type: regular
    task:
      id: 96d5c029-f41c-45a2-84ed-1224e24fe6c3
      version: -1
      name: All is good
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: All is good
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 860,
          "y": 1230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 5bcb519e-4979-49d7-81f5-a0aed967d497
    type: regular
    task:
      id: 5bcb519e-4979-49d7-81f5-a0aed967d497
      version: -1
      name: Failed verifying data
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: Failed verifying debug log
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 350,
          "y": 1240
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1305,
        "width": 890,
        "x": 350,
        "y": 30
      }
    }
  }
inputs: []
outputs: []
fromversion: 5.0.0
description: ''
