commonfields:
  id: 4f1d18f1-fdc9-414f-8a75-4cccf7259e33
  version: 10
name: TestPyLogging
script: |
  import logging

  root_logger = logging.getLogger()

  logging.debug("logging: this is a test")
  demisto.results("done debug test. handlers: {}".format(root_logger.handlers))
type: python
tags: []
enabled: true
scripttarget: 0
subtype: python3
pswd: ""
runonce: false
dockerimage: demisto/python3:3.7.3.286
runas: DBotWeakRole
