id: CVE Search v2 - Test
version: -1
name: CVE Search v2 - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 04efab76-ea5f-4bb8-8abb-8ae5caa5514a
    type: start
    task:
      id: 04efab76-ea5f-4bb8-8abb-8ae5caa5514a
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 009efa4c-e109-4643-8b03-2c606f58ea7f
    type: regular
    task:
      id: 009efa4c-e109-4643-8b03-2c606f58ea7f
      version: -1
      name: Populate Error
      description: commands.local.cmd.get.entry
      script: Builtin|||getEntry
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      extend-context:
        simple: PreviousTaskOutput=
      id:
        simple: ${lastCompletedTaskEntries}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: 7b317677-6e1a-4183-8d02-50fc844ebfa4
    type: condition
    task:
      id: 7b317677-6e1a-4183-8d02-50fc844ebfa4
      version: -1
      name: Check if cve-latest return 30 entries
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualNumber
          left:
            value:
              complex:
                root: CVE
                accessor: ID
                transformers:
                - operator: count
            iscontext: true
          right:
            value:
              simple: "30"
    view: |-
      {
        "position": {
          "x": 265,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: d0d12ea6-7543-43e8-80a4-0585358269f4
    type: regular
    task:
      id: d0d12ea6-7543-43e8-80a4-0585358269f4
      version: -1
      name: cve-latest
      description: Retruns the latest updated CVEs.
      script: CVE Search v2|||cve-latest
      type: regular
      iscommand: true
      brand: CVE Search v2
    nexttasks:
      '#none#':
      - "5"
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: a50447f1-5e69-409b-8969-710bc0e79c27
    type: regular
    task:
      id: a50447f1-5e69-409b-8969-710bc0e79c27
      version: -1
      name: Check cve
      description: Returns CVE information by CVE ID.
      script: CVE Search v2|||cve
      type: regular
      iscommand: true
      brand: CVE Search v2
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      cve_id:
        simple: CVE-2015-6541
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: 2cdc7eab-e02c-4228-8185-25e8398007e9
    type: regular
    task:
      id: 2cdc7eab-e02c-4228-8185-25e8398007e9
      version: -1
      name: Populate Error
      description: commands.local.cmd.get.entry
      script: Builtin|||getEntry
      type: regular
      iscommand: true
      brand: Builtin
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      extend-context:
        simple: PreviousTaskOutput=
      id:
        simple: ${lastCompletedTaskEntries}
    continueonerror: true
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 2b1eb4c8-f3e6-4309-845d-c5b92e9bb0e1
    type: condition
    task:
      id: 2b1eb4c8-f3e6-4309-845d-c5b92e9bb0e1
      version: -1
      name: Validate Error type
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "12"
      "yes":
      - "11"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: endWith
          left:
            value:
              simple: PreviousTaskOutput
            iscontext: true
          right:
            value:
              simple: (read timeout=10)
    view: |-
      {
        "position": {
          "x": 60,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: ee9faeca-a5f3-4dc9-8e4e-28f1d92d36f1
    type: regular
    task:
      id: ee9faeca-a5f3-4dc9-8e4e-28f1d92d36f1
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 0b683ae7-91d5-44ea-8038-293a8ac608be
    type: title
    task:
      id: 0b683ae7-91d5-44ea-8038-293a8ac608be
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 695,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: bfae8e79-c506-4651-827f-b24fb814a098
    type: regular
    task:
      id: bfae8e79-c506-4651-827f-b24fb814a098
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: cve-latest did not return 30 last entires
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 5f8578ef-b1a9-4d0e-8756-3c0e87148057
    type: condition
    task:
      id: 5f8578ef-b1a9-4d0e-8756-3c0e87148057
      version: -1
      name: Validate Error type
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "9"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: endWith
          left:
            value:
              simple: PreviousTaskOutput
            iscontext: true
          right:
            value:
              simple: (read timeout=10)
    view: |-
      {
        "position": {
          "x": 275,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: a6209cf6-b55f-46ed-81f0-f981340a6915
    type: regular
    task:
      id: a6209cf6-b55f-46ed-81f0-f981340a6915
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: d1893bed-9751-4ad6-8317-59888744e2b6
    type: regular
    task:
      id: d1893bed-9751-4ad6-8317-59888744e2b6
      version: -1
      name: Error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: cve-latest did not return 30 last entires
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 68a33207-da5f-4cb9-86e4-b256ee5dd0e5
    type: regular
    task:
      id: 68a33207-da5f-4cb9-86e4-b256ee5dd0e5
      version: -1
      name: Delete context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 4d2c918d-4a32-4be1-82c7-79798ea94d72
    type: condition
    task:
      id: 4d2c918d-4a32-4be1-82c7-79798ea94d72
      version: -1
      name: Check cve results
      type: condition
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CVE.ID
            iscontext: true
          right:
            value:
              simple: CVE-2015-6541
      - - operator: isEqualNumber
          left:
            value:
              simple: CVE.CVSS
            iscontext: true
          right:
            value:
              simple: "6.8"
      - - operator: isEqualString
          left:
            value:
              simple: CVE.Published
            iscontext: true
          right:
            value:
              simple: 2016-04-08T14:59:00
      - - operator: isEqualString
          left:
            value:
              simple: CVE.Modified
            iscontext: true
          right:
            value:
              simple: 2016-04-11T17:44:00
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 1025,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
fromversion: 4.1.0
description: ''
