id: PcapMiner Playbook
version: -1
name: PcapMiner Playbook
description: This playbook only launches the PCAP Miner script. It is used in the
  `Pcap Miner (Large Files)` playbook and is equivalent to running the `PcapMinerV2`
  script.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 3654cd42-4e5f-496b-8ded-4211f12fc34d
    type: start
    task:
      id: 3654cd42-4e5f-496b-8ded-4211f12fc34d
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 68db7045-9b58-43df-8395-dc10d27ea240
    type: regular
    task:
      id: 68db7045-9b58-43df-8395-dc10d27ea240
      version: -1
      name: Pcap Miner V2
      description: PcapMIner V2 allows to parse pcap files by displaying the all of
        the relevant data within including ip addresses, ports, flows, specific protocol
        breakdown, searching by regex, decrypting encrypted  traffic and more.
      scriptName: PcapMinerV2
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      convs_to_display:
        simple: ${inputs.convs_to_display}
      custom_regex:
        simple: ${inputs.custom_regex}
      entry_id:
        simple: ${inputs.entry_id}
      extract_ips: {}
      extract_strings:
        simple: ${inputs.extract_strings}
      filtered_file_name:
        simple: ${inputs.filtered_file_name}
      iterate:
        simple: "True"
      packets_to_analyze:
        simple: ${inputs.packets_to_analyze}
      pcap_filter:
        simple: ${inputs.pcap_filter}
      protocol_output:
        simple: ${inputs.protocol_output}
      rsa_decrypt_key_entry_id:
        simple: ${inputs.rsa_decrypt_key_entry_id}
      wpa_password:
        simple: ${inputs.wpa_password}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: bd68598a-ebd2-4bfd-80f9-846463f9e116
    type: title
    task:
      id: bd68598a-ebd2-4bfd-80f9-846463f9e116
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 375,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: entry_id
  value: {}
  required: false
  description: The entry_id of the PCAP file to mine.
  playbookInputQuery:
- key: protocol_output
  value: {}
  required: false
  description: What protocols to output as context. Could be multiple protocols separated
    by commas. If left empty will not output any protocols to context.
  playbookInputQuery:
- key: extract_strings
  value: {}
  required: false
  description: Whether to  extract IP, URL and Email from PCAP file.
  playbookInputQuery:
- key: pcap_filter
  value: {}
  required: false
  description: 'Filter to apply on PCAP. Wireshark syntax as can be found here: https://www.wireshark.org/docs/man-pages/wireshark-filter.html'
  playbookInputQuery:
- key: custom_regex
  value: {}
  required: false
  description: Your own regular expression to extract from the PCAP.
  playbookInputQuery:
- key: filtered_file_name
  value: {}
  required: false
  description: The name of the PCAP file to save to the war room after applying the
    `pcap_filter` (i.e. `filtered_file.pcap`).
  playbookInputQuery:
- key: rsa_decrypt_key_entry_id
  value: {}
  required: false
  description: The entry ID for the RSA decryption key.
  playbookInputQuery:
- key: convs_to_display
  value: {}
  required: false
  description: Number of conversatinos to display.
  playbookInputQuery:
- key: wpa_password
  value: {}
  required: false
  description: The WPA password. By providing the password you will be able to decrypt
    encrypted traffic data.
  playbookInputQuery:
- key: extract_ips
  value: {}
  required: false
  description: Output to context the source and destination IPs in the PCAP file.
  playbookInputQuery:
- key: packets_to_analyze
  value: {}
  required: false
  description: The number of packets to analyze at each iteration of this playbook.
    Recommended not over 50,000.
  playbookInputQuery:
- key: iterate
  value: {}
  required: false
  description: Whether this run of the playbook is an iteration of a large PCAP file.
  playbookInputQuery:
outputs:
- contextPath: PcapResults
  type: unknown
- contextPath: PcapResults.Bytes
  description: The number of bytes transmitted in the PCAP file.
  type: Number
- contextPath: PcapResults.Packets
  description: The number of packets transmitted in the PCAP file.
  type: Number
- contextPath: PcapResults.EntryID
  description: The entryID of the PCAP file.
  type: String
- contextPath: PcapResults.StreamCount
  description: The number of streams in the PCAP file.
  type: String
- contextPath: PcapResults.StartTime
  description: The date and time of the first packet in the PCAP file.
  type: Date
- contextPath: PcapResults.EndTime
  description: The date and time of the last packet in the PCAP file.
  type: String
- contextPath: PcapResults.UniqueSourceIP
  description: The number of unique IPs from which packets were transmitted.
  type: Number
- contextPath: PcapResults.UniqueDestIP
  description: The number of unique IPs from to packets were transmitted.
  type: Number
- contextPath: PcapResults.URL
  description: The URLs extracted from the file.
  type: String
- contextPath: PcapResults.IP
  description: The IPs extracted from the file.
  type: String
- contextPath: PcapResults.Email
  description: The emails extracted from the file.
  type: String
- contextPath: PcapResults.Regex
  description: The regular expressions specified in `extract_regex`,extracted from
    the file
  type: String
- contextPath: PcapResults.Protocols
  description: List of protocls found in the PCAP.
  type: String
- contextPath: PcapResultsFlow.Bytes
  description: The number of bytes transmitted in the flow.
  type: String
- contextPath: PcapResultsFlow.DestIP
  description: The destination IP of the flow.
  type: String
- contextPath: PcapResultsFlow.SourceIP
  description: The source IP of the flow.
  type: String
- contextPath: PcapResultsFlow.SourcePort
  description: The source port of the flow.
  type: String
- contextPath: PcapResultsFlow.Duration
  description: The duration of the flow (in seconds).
  type: String
- contextPath: PcapResultsFlow.DestPort
  description: The destination port of the flow.
  type: String
- contextPath: PcapResultsFlow.EndTime
  description: The date time the flow ended.
  type: Date
- contextPath: PcapResultsFlow.StartTime
  description: The date time the flow started.
  type: Date
- contextPath: PcapResultsHTTP.ResponseStatusCode
  description: The response code.
  type: String
- contextPath: PcapResultsHTTP.RequestVersion
  description: The request version.
  type: String
- contextPath: PcapResultsHTTP.RequestCacheControl
  description: The chache control of the request.
  type: String
- contextPath: PcapResultsHTTP.ResponseDate
  description: The time and date of the response.
  type: Date
- contextPath: PcapResultsHTTP.RequestMethod
  description: The request method.
  type: String
- contextPath: PcapResultsHTTP.RequestSourceIP
  description: The source IP of the request.
  type: String
- contextPath: PcapResultsHTTP.ResponseContentType
  description: The response content type.
  type: String
- contextPath: PcapResultsHTTP.RequestAgent
  description: The request agent.
  type: String
- contextPath: PcapResultsHTTP.RequestHost
  description: The request host.
  type: String
- contextPath: PcapResultsHTTP.ResponseVersion
  description: The response version.
  type: String
- contextPath: PcapResultsHTTP.ID
  description: The ID of the http interaction.
  type: String
- contextPath: PcapResultsHTTP.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsHTTP.RequestURI
  description: The request URI.
  type: String
- contextPath: PcapResultsHTTP.ResponseContentLength
  description: The length of the rescponse content.
  type: String
- contextPath: PcapResultsHTTP.ResponseCodeDesc
  description: The code description of the response.
  type: String
- contextPath: PcapResultsDNS.ID
  description: The ID of the DNS request.
  type: String
- contextPath: PcapResultsDNS.Request
  description: The DNS request.
  type: String
- contextPath: PcapResultsDNS.Response
  description: The DNS response.
  type: String
- contextPath: PcapResultsDNS
  type: unknown
- contextPath: PcapResultsDNS.Type
  description: The type of the DNS request.
  type: String
- contextPath: PcapResultsDNS.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsSMTP
  type: unknown
- contextPath: PcapResultsSMTP.From
  description: Who the mail is from.
  type: String
- contextPath: PcapResultsSMTP.To
  description: To whom the mail is.
  type: String
- contextPath: PcapResultsSMTP.Subject
  description: The mail subject.
  type: String
- contextPath: PcapResultsSMTP.MimeVersion
  description: The mime version.
  type: String
- contextPath: PcapResultsSMTP.ID
  description: The SMTP packet's ID.
  type: String
- contextPath: PcapResultsSMTP.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsKERBEROS
  type: unknown
- contextPath: PcapResultsKERBEROS.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsKERBEROS.Realm
  description: The KERBEROS's realm.
  type: String
- contextPath: PcapResultsKERBEROS.SName
  description: The KERBEROS's SName.
  type: String
- contextPath: PcapResultsKERBEROS.CName
  description: The KERBEROS's CName.
  type: String
- contextPath: PcapResultsTelnet
  type: unknown
- contextPath: PcapResultsTelnet.Data
  description: The Telnet data.
  type: String
- contextPath: PcapResultsTelnet.Commands
  description: The telnet commands.
  type: String
- contextPath: PcapResultsTelnet.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsLLMNR
  type: unknown
- contextPath: PcapResultsLLMNR.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsLLMNR.QueryClass
  description: The LLMNR's query class.
  type: String
- contextPath: PcapResultsLLMNR.QueryName
  description: The LLMNR's query name.
  type: String
- contextPath: PcapResultsLLMNR.Questions
  description: The LLMNR questions.
  type: String
- contextPath: PcapResultsLLMNR.ID
  description: The LLMNR's packet ID.
  type: String
- contextPath: PcapResultsLLMNR.QueryType
  description: The LLMNR's query type.
  type: String
- contextPath: PcapResultsSMB2
  type: unknown
- contextPath: PcapResultsSMB2.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsSMB2.ID
  description: The  SMB2's packet ID.
  type: String
- contextPath: PcapResultsSMB2.UserName
  description: The  SMB2's user name.
  type: String
- contextPath: PcapResultsSMB2.Domain
  description: The  SMB2's domain.
  type: String
- contextPath: PcapResultsSMB2.HostName
  description: The  SMB2's host name.
  type: String
- contextPath: PcapResultsSMB2.Command
  description: The  SMB2's command.
  type: String
- contextPath: PcapResultsSMB2.FileName
  description: The  SMB2's file name.
  type: String
- contextPath: PcapResultsSMB2.Tree
  description: The  SMB2's tree.
  type: String
- contextPath: PcapResultsNETBIOS
  type: unknown
- contextPath: PcapResultsNETBIOS.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsNETBIOS.ID
  description: The  NETIOS's packet ID.
  type: String
- contextPath: PcapResultsNETBIOS.Name
  description: The  NETIOS's name.
  type: String
- contextPath: PcapResultsNETBIOS.Type
  description: The  NETIOS's type.
  type: String
- contextPath: PcapResultsNETBIOS.Class
  description: The  NETIOS's class.
  type: String
- contextPath: PcapResultsIRC
  type: unknown
- contextPath: PcapResultsIRC.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsIRC.ID
  description: The  IRC's packet ID.
  type: String
- contextPath: PcapResultsIRC.RequestCommand
  description: The  IRC's request command.
  type: String
- contextPath: PcapResultsIRC.RequestTrailer
  description: The  IRC's request trailer.
  type: String
- contextPath: PcapResultsIRC.RequestPrefix
  description: The  IRC's request prefix.
  type: String
- contextPath: PcapResultsIRC.RequestParameters
  description: The  IRC's request parameters.
  type: String
- contextPath: PcapResultsIRC.ResponseCommand
  description: The  IRC's response command.
  type: String
- contextPath: PcapResultsIRC.ResponseTrailer
  description: The  IRC's response trailers.
  type: String
- contextPath: PcapResultsIRC.ResponsePrefix
  description: The  IRC's response prefix.
  type: String
- contextPath: PcapResultsIRC.ResponseParameters
  description: The  IRC's response parameters.
  type: String
- contextPath: PcapResultsFTP
  type: unknown
- contextPath: PcapResultsFTP.EntryID
  description: The PCAP's entry ID.
  type: String
- contextPath: PcapResultsFTP.ID
  description: The  FTP's packet ID.
  type: String
- contextPath: PcapResultsFTP.RequestCommand
  description: The  FTP's request command.
  type: String
- contextPath: PcapResultsFTP.ResponseCode
  description: The  FTP's response code.
  type: String
- contextPath: PcapResultsFTP.ResponseArgs
  description: The  FTP's response arguments.
  type: String
fromversion: 5.0.0
tests:
- No tests (auto formatted)
